### PR TITLE
Assignment finished

### PR DESCRIPTION
**Pull request by C3ra906**
Hello, I finished HW1 and would like your feedback on my coding style or any mistakes I may have made. Thank you so much!

### CODE REVIEW

**Comment by schoure98** [comment]
Hey, I guess made the commit to your code. Sorry for the mess up.  
The JS code looks clean. Simple and easy to understand. Good job.

**Comment by C3ra906** [comment]
> Hey, I guess made the commit to your code. Sorry for the mess up. The JS code looks clean. Simple and easy to understand. Good job.

No worries, asking Caterina and Jeremy what to do about it : ) 

Update: Caterina says it's okay that it was merged as long as I get two reviews on it. Thanks everyone!

**Comment by JeremiahTilse** [comment]
It looks like the pull request has already been merged.  

This looks good.  I only have one real suggestion:
- change `i++` to `i += 1` to meet Airbnb guidelines.  See [16.2](https://github.com/airbnb/javascript#blocks--cuddled-elses)

The nested if/else statements may make it difficult for someone editing the code later, but the code works as needed.  I other than that, I don't see a reason to change it.

Strong work!

**Comment by C3ra906** [comment]
> It looks like the pull request has already been merged.
> 
> This looks good. I only have one real suggestion:
> 
> * change `i++` to `i += 1` to meet Airbnb guidelines.  See [16.2](https://github.com/airbnb/javascript#blocks--cuddled-elses)
> 
> The nested if/else statements may make it difficult for someone editing the code later, but the code works as needed. I other than that, I don't see a reason to change it.
> 
> Strong work!

Thanks for the feedback Jeremiah! I will remember to use i += 1 next time!

**Pull request merged**
